server:
  port: 8767
spring:
  application:
    name: server-zuul
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 192.168.1.199
    port: 6379
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 10000
      shutdown-timeout: 10000
eureka:
  instance:
    hostname: 172.17.0.2
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: web-api-cli
    api-b:
      path: /api-b/**
      serviceId: web-api-cli
