server:
    port: 8765
spring:
  application:
    name: web-api-cli
  redis:
    database: 0
    host: 192.168.1.199
    port: 6379
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 10000
      shutdown-timeout: 10000
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
        probability: 1
eureka:
    instance:
      hostname: 172.17.0.2
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
